weights:
  base: 50

  # speed buckets (km/h)
  speed_low_bonus: 20      # <= 30
  speed_mid_bonus: 10      # 31–50
  speed_high_penalty: -10  # > 50

  lit_yes_bonus: 15
  lit_no_penalty: -10

  sidewalk_bonus: 10       # any of [both,left,right]
  sidewalk_no_penalty: -5

  nodes_short_bonus: 5     # n_nodes <= 5
  nodes_long_penalty: -10  # n_nodes >= 50

caps:
  min: 0
  max: 100

# relative risk per OSM highway type
highway_risk:
  motorway: -15
  trunk: -10
  primary: -5
  secondary: -2
  tertiary: -1
  residential: 0
  service: 0
  living_street: 5
  footway: 10
  pedestrian: 8
  